#define ASSIGN 1
#define IDENTIFIER 2
#define INTEGER 3
#define DEFAULT "none"
#define END 4
#define DOUBLE 5
#define B_OPENING 6
#define B_CLOSING 7
#define S_OPENING 8
#define S_CLOSING 9
#define IF 10
#define ELSE 11
#define WHILE 12
#define DO  13
#define FOR 14
